# Generated by Django 2.0.6 on 2018-06-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='pic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
