# Generated by Django 2.0.6 on 2018-06-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timeline_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
