# Generated by Django 2.0.6 on 2018-06-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0002_timeline_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Timeline')),
            ],
        ),
    ]
